apiVersion: apps/v1
kind: Deployment
# ------- Deployment Configuration -----------> Ensures that the is always pod running
metadata:
  name: apm-app
  labels:
    name: apm-app
spec:
  selector:
    matchLabels:
      service: apm-app
  replicas: 1
# ------- Pod Configuration ---------> Specify the pod parameters
  template:
    metadata:
      name: apm-app
      labels:
        service: apm-app
      annotations: 
        prometheus.io/scrape: "true"
        admission.datadoghq.com/enabled: "true"
    spec:
# ------- Container Configuration ---------> Specify the container parameters
      containers:
        - name: apm-app
          image: ccdaniele/apm-test:v1
          imagePullPolicy: Always
          ports:
            - name: client-port
              containerPort: 3000
