apiVersion: v1
kind: Pod
metadata:
  name: apm-app-pod
  labels:
    app: apm-app
  annotations:
    prometheus.io/scrape: "true"
spec:
  containers:
    - name: apm-app
      image: myrepo/myimagename:mytag
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3000
          name: client-port
