apiVersion: "datadoghq.com/v2alpha1"
kind: "DatadogAgent"
metadata:
  name: "datadog"
spec:
  global:
    site: "datadoghq.com"
    clusterName: apm-test
    kubelet:
      tlsVerify: false
    credentials:
      apiSecret:
        secretName: "datadog-secret"
        keyName: "api-key"
  features:
    liveProcessCollection:
      enabled: true
    logCollection:
      enabled: true
    apm:
      instrumentation:
        enabled: false
  override:
    nodeAgent:
      env:
        - name: DD_HOSTNAME_TRUST_UTS_NAMESPACE
          value: "true"
        - name: DD_USE_FQDN
          value: "false"
