apiVersion: "datadoghq.com/v2alpha1"
kind: "DatadogAgent"
metadata:
  name: "datadog"
spec:
  global:
    clusterName: "apm-test"
    site: "datadoghq.com"
    tlsVerify: false
    tags:
      - "env:apm-test"
    credentials:
      apiSecret:
        secretName: "datadog-secret"
        keyName: "api-key"
